### ISSUE TITLE
I'm gonna give it a shot caleb thanks for this =)

### ISSUE THREAD

**Issue by Gaspa79** [Caleb-Petersen/BlindfoldTrainer#2]
sorry for posting this as an issue. Please close.

Also I can't believe I found this by mere chance lol

**Comment by Caleb-Petersen** [comment]
Glad you're trying it out! I just updated it with a few feature fixes, including properly speaking moves that require an origin file or row (e.g. Nbd7 or R1e5), so it is probably worth it for you to use the most recent version if you're going to try practicing with it much.
